### ISSUE TITLE
Crash server when I right click on composter.

### ISSUE THREAD

**Issue by DaDiGui** [Stormwind99/Composter#23]
```Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.wumple.composter.capability.CompostBinCap.always(CompostBinCap.java:528)
	at com.wumple.util.capability.tickingthing.TickingThingCap.handleOnTick(TickingThingCap.java:166)
	at com.wumple.util.capability.tickingthing.TickingThingCap.onTick(TickingThingCap.java:181)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_246_TickingThingCap_onTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:289)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:966)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Unknown Source)```

**Comment by YukiSuter** [comment]
Same issue, only happens on server, not in singleplayer.
